export type {
  AttackLogEntry,
  ChannelParticipantSnapshot,
  DepravedSuicideLogEntry,
  DivinationLogEntry,
  ExecutionLogEntry,
  FoxCurseLogEntry,
  Game,
  GameActionType,
  GameId,
  GameLogEntry,
  GamePhaseInfo,
  GameResultLogEntry,
  GuardLogEntry,
  MediumLogEntry,
  PlayerStateForWin,
  VictimLogEntry,
  VoteLogEntry,
} from "./game.types.js";
export { GameLogType, GameOutcome, PlayerTeam } from "./game.types.js";
export {
  applyResultToLogs,
  buildDepravedSuicideLog,
  buildExecutionLog,
  buildFoxCurseLog,
  buildMediumLog,
  buildNewGameCreatePayload,
  buildPlayersFromParticipants,
  buildRandomTargetLogs,
  buildShuffledRoleOrder,
  buildVictimLog,
  computeNextPhaseAt,
  detectPlayerTeam,
  doesAttackSucceed,
  ensureGameExists,
  ensureParticipantCountMatchesRoleCount,
  extractTargetFromLog,
  getAliveConfiguredRoleKeys,
  getAliveTraitorIds,
  getAttackTargetId,
  getConfiguredRoles,
  getExecutionTargetByVotes,
  getGameOutcome,
  getGameOutcomeFromPlayers,
  getGuardTargetId,
  getNextPhase,
  getPhaseDurationMinutes,
  getPhaseDurationMs,
  getRandomAlivePlayer,
  getRolesMissingLog,
  isTargetFox,
  ROLE_TO_NIGHT_LOG_TYPE,
} from "./game.domain.js";
export type { NextPhaseResult } from "./game.domain.js";
export {
  ACTION_CONDITION_MAP,
  canReceiveRequest,
  existsActionRequest,
  judgeByActionCondition,
  judgeByCommonCondition,
  upsertActionRequest,
} from "./game.action.js";
export type { GameActionContext } from "./game.action.js";
export {
  buildGameEndSystemMessage,
  buildNightActionResultSystemMessage,
  buildPreGameSystemMessage,
  buildVoteResultSystemMessage,
} from "./game.system-messages.js";
